#Variables that contains the user credentials to access Twitter API 
ACCESS_TOKEN = "ENTER YOUR ACCESS TOKEN"
ACCESS_TOKEN_SECRET = "ENTER YOUR ACCESS TOKEN SECRET"
CONSUMER_KEY = "ENTER YOUR API KEY"
CONSUMER_SECRET = "ENTER YOUR API SECRET"